# Generated by Django 4.2.7 on 2025-06-13 09:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="following",
            field=models.ManyToManyField(
                help_text="用戶關注的其他用戶",
                related_name="followers",
                through="accounts.Follow",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
