# Generated by Django 5.2.1 on 2025-05-24 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('follow', '關注'), ('like', '點讚'), ('comment', '評論'), ('reply', '回覆'), ('mention', '提及'), ('message', '私信'), ('share', '分享'), ('system', '系統通知')], max_length=20, unique=True, verbose_name='通知類型')),
                ('title_template', models.CharField(help_text='支持變量替換，如 {actor_name}, {target_name} 等', max_length=200, verbose_name='標題模板')),
                ('message_template', models.TextField(help_text='支持變量替換，如 {actor_name}, {target_name} 等', verbose_name='內容模板')),
                ('email_subject_template', models.CharField(blank=True, max_length=200, verbose_name='郵件主題模板')),
                ('email_body_template', models.TextField(blank=True, verbose_name='郵件內容模板')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
            ],
            options={
                'verbose_name': '通知模板',
                'verbose_name_plural': '通知模板',
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_notifications', models.BooleanField(default=True, help_text='有人關注你時接收通知', verbose_name='關注通知')),
                ('like_notifications', models.BooleanField(default=True, help_text='有人點讚你的內容時接收通知', verbose_name='點讚通知')),
                ('comment_notifications', models.BooleanField(default=True, help_text='有人評論你的內容時接收通知', verbose_name='評論通知')),
                ('reply_notifications', models.BooleanField(default=True, help_text='有人回覆你的評論時接收通知', verbose_name='回覆通知')),
                ('mention_notifications', models.BooleanField(default=True, help_text='有人在內容中提及你時接收通知', verbose_name='提及通知')),
                ('message_notifications', models.BooleanField(default=True, help_text='收到私信時接收通知', verbose_name='私信通知')),
                ('share_notifications', models.BooleanField(default=True, help_text='有人分享你的內容時接收通知', verbose_name='分享通知')),
                ('system_notifications', models.BooleanField(default=True, help_text='接收系統更新、新功能通知', verbose_name='系統通知')),
                ('email_notifications', models.BooleanField(default=True, help_text='通過郵件接收通知', verbose_name='郵件通知')),
                ('push_notifications', models.BooleanField(default=True, help_text='通過瀏覽器推送接收通知', verbose_name='推送通知')),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='勿擾時間段開始時間', null=True, verbose_name='勿擾時間開始')),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='勿擾時間段結束時間', null=True, verbose_name='勿擾時間結束')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '通知設置',
                'verbose_name_plural': '通知設置',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('follow', '關注'), ('like', '點讚'), ('comment', '評論'), ('reply', '回覆'), ('mention', '提及'), ('message', '私信'), ('share', '分享'), ('system', '系統通知')], help_text='通知的類型分類', max_length=20, verbose_name='通知類型')),
                ('title', models.CharField(help_text='通知的標題', max_length=200, verbose_name='通知標題')),
                ('message', models.TextField(help_text='通知的詳細內容', verbose_name='通知內容')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='對象ID')),
                ('data', models.JSONField(blank=True, default=dict, help_text='通知相關的額外數據', verbose_name='額外數據')),
                ('is_read', models.BooleanField(default=False, help_text='通知是否已被閱讀', verbose_name='已讀狀態')),
                ('is_sent', models.BooleanField(default=False, help_text='通知是否已通過其他管道發送（如郵件、推送）', verbose_name='已發送狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='閱讀時間')),
                ('expires_at', models.DateTimeField(blank=True, help_text='通知的過期時間，過期後自動清理', null=True, verbose_name='過期時間')),
                ('actor', models.ForeignKey(blank=True, help_text='觸發通知的用戶（系統通知可為空）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='觸發者')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='內容類型')),
                ('recipient', models.ForeignKey(help_text='接收通知的用戶', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收者')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_f39341_idx'), models.Index(fields=['type', 'created_at'], name='notificatio_type_8e213d_idx')],
            },
        ),
    ]
