# Generated by Django 5.2.1 on 2025-05-24 05:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('participants', models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='參與者')),
            ],
            options={
                'verbose_name': '對話',
                'verbose_name_plural': '對話',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(verbose_name='內容')),
                ('message_type', models.CharField(choices=[('text', '文字'), ('image', '圖片'), ('video', '影片'), ('file', '文件')], default='text', max_length=10, verbose_name='訊息類型')),
                ('file', models.FileField(blank=True, null=True, upload_to='chat_files/', verbose_name='文件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='發送時間')),
                ('is_read', models.BooleanField(default=False, verbose_name='已讀')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='閱讀時間')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation', verbose_name='對話')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='發送者')),
            ],
            options={
                'verbose_name': '訊息',
                'verbose_name_plural': '訊息',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserConversationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archived', models.BooleanField(default=False, verbose_name='已封存')),
                ('unread_count', models.PositiveIntegerField(default=0, verbose_name='未讀消息數')),
                ('last_read_at', models.DateTimeField(blank=True, null=True, verbose_name='最後讀取時間')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='chat.conversation', verbose_name='對話')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_states', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '用戶對話狀態',
                'verbose_name_plural': '用戶對話狀態',
                'unique_together': {('user', 'conversation')},
            },
        ),
    ]
