# Generated by Django 5.2.1 on 2025-05-24 05:52

import django.core.validators
import django.db.models.deletion
import posts.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='貼文唯一標識符', primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='貼文內容')),
                ('code_snippet', models.TextField(blank=True, help_text='程式碼片段（最多100行）')),
                ('code_language', models.CharField(blank=True, help_text='程式語言（自動檢測）', max_length=50)),
                ('code_highlighted', models.TextField(blank=True, help_text='高亮後的HTML代碼')),
                ('likes_count', models.PositiveIntegerField(default=0, help_text='點讚數量')),
                ('comments_count', models.PositiveIntegerField(default=0, help_text='評論數量')),
                ('shares_count', models.PositiveIntegerField(default=0, help_text='分享數量')),
                ('views_count', models.PositiveIntegerField(default=0, help_text='瀏覽數量')),
                ('is_published', models.BooleanField(default=True, help_text='是否已發布')),
                ('is_featured', models.BooleanField(default=False, help_text='是否為精選貼文')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新時間')),
                ('author', models.ForeignKey(help_text='貼文作者', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '貼文',
                'verbose_name_plural': '貼文',
                'db_table': 'posts_post',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='點讚時間')),
                ('user', models.ForeignKey(help_text='點讚用戶', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(help_text='被點讚的貼文', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.post')),
            ],
            options={
                'verbose_name': '點讚',
                'verbose_name_plural': '點讚',
                'db_table': 'posts_like',
            },
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('image', '圖片'), ('video', '影片')], help_text='媒體類型', max_length=10)),
                ('file', models.FileField(help_text='媒體文件', upload_to=posts.models.get_post_media_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'mp4', 'webm', 'avi'])])),
                ('alt_text', models.CharField(blank=True, help_text='替代文字（用於無障礙）', max_length=200)),
                ('thumbnail', models.ImageField(blank=True, help_text='縮略圖（影片使用）', null=True, upload_to='thumbnails/')),
                ('order', models.PositiveIntegerField(default=0, help_text='顯示順序')),
                ('file_size', models.PositiveIntegerField(default=0, help_text='文件大小（字節）')),
                ('width', models.PositiveIntegerField(default=0, help_text='寬度（像素）')),
                ('height', models.PositiveIntegerField(default=0, help_text='高度（像素）')),
                ('duration', models.FloatField(blank=True, help_text='持續時間（秒，僅影片）', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='創建時間')),
                ('post', models.ForeignKey(help_text='所屬貼文', on_delete=django.db.models.deletion.CASCADE, related_name='media', to='posts.post')),
            ],
            options={
                'verbose_name': '貼文媒體',
                'verbose_name_plural': '貼文媒體',
                'db_table': 'posts_post_media',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='轉發記錄唯一標識符', primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, help_text='轉發時的評論')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='轉發時間')),
                ('post', models.ForeignKey(help_text='被轉發的貼文', on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='posts.post')),
                ('user', models.ForeignKey(help_text='轉發用戶', on_delete=django.db.models.deletion.CASCADE, related_name='shared_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '貼文轉發',
                'verbose_name_plural': '貼文轉發',
                'db_table': 'posts_postshare',
            },
        ),
        migrations.CreateModel(
            name='PostView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='瀏覽記錄唯一標識符', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='瀏覽時間')),
                ('duration', models.PositiveIntegerField(default=0, help_text='瀏覽時長（秒）')),
                ('source', models.CharField(choices=[('recommendation', '推薦'), ('search', '搜尋'), ('following', '關注'), ('trending', '熱門'), ('direct', '直接訪問'), ('profile', '個人頁面')], default='direct', help_text='瀏覽來源', max_length=50)),
                ('post', models.ForeignKey(help_text='被瀏覽的貼文', on_delete=django.db.models.deletion.CASCADE, related_name='view_records', to='posts.post')),
                ('user', models.ForeignKey(help_text='瀏覽用戶', on_delete=django.db.models.deletion.CASCADE, related_name='post_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '貼文瀏覽記錄',
                'verbose_name_plural': '貼文瀏覽記錄',
                'db_table': 'posts_postview',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('spam', '垃圾內容'), ('harassment', '騷擾'), ('hate_speech', '仇恨言論'), ('violence', '暴力內容'), ('inappropriate', '不當內容'), ('copyright', '版權侵犯'), ('false_info', '虛假信息'), ('other', '其他')], help_text='舉報原因', max_length=20)),
                ('description', models.TextField(blank=True, help_text='詳細描述')),
                ('status', models.CharField(choices=[('pending', '待處理'), ('reviewed', '已審核'), ('resolved', '已解決'), ('dismissed', '已駁回')], default='pending', help_text='處理狀態', max_length=20)),
                ('reviewer_notes', models.TextField(blank=True, help_text='審核備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='舉報時間')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='審核時間', null=True)),
                ('post', models.ForeignKey(help_text='被舉報的貼文', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='posts.post')),
                ('reporter', models.ForeignKey(help_text='舉報者', on_delete=django.db.models.deletion.CASCADE, related_name='post_reports_made', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, help_text='審核者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_reports_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '舉報',
                'verbose_name_plural': '舉報',
                'db_table': 'posts_report',
            },
        ),
        migrations.CreateModel(
            name='Save',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='收藏時間')),
                ('post', models.ForeignKey(help_text='被收藏的貼文', on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='posts.post')),
                ('user', models.ForeignKey(help_text='收藏用戶', on_delete=django.db.models.deletion.CASCADE, related_name='saved_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
                'db_table': 'posts_save',
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', '-created_at'], name='posts_post_author__f8ea20_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='posts_post_created_183a3b_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_published', '-created_at'], name='posts_post_is_publ_ca885b_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_featured', '-created_at'], name='posts_post_is_feat_0952cf_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['likes_count'], name='posts_post_likes_c_18e5ed_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['comments_count'], name='posts_post_comment_7c7913_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['user', '-created_at'], name='posts_like_user_id_92ce02_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['post', '-created_at'], name='posts_like_post_id_476f02_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'post')},
        ),
        migrations.AddIndex(
            model_name='postmedia',
            index=models.Index(fields=['post', 'order'], name='posts_post__post_id_2f6517_idx'),
        ),
        migrations.AddIndex(
            model_name='postmedia',
            index=models.Index(fields=['media_type'], name='posts_post__media_t_488eda_idx'),
        ),
        migrations.AddIndex(
            model_name='postshare',
            index=models.Index(fields=['user', '-created_at'], name='posts_posts_user_id_f45a62_idx'),
        ),
        migrations.AddIndex(
            model_name='postshare',
            index=models.Index(fields=['post', '-created_at'], name='posts_posts_post_id_7373c3_idx'),
        ),
        migrations.AddIndex(
            model_name='postshare',
            index=models.Index(fields=['-created_at'], name='posts_posts_created_9c9c1a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postshare',
            unique_together={('user', 'post')},
        ),
        migrations.AddIndex(
            model_name='postview',
            index=models.Index(fields=['user', '-created_at'], name='posts_postv_user_id_63b63f_idx'),
        ),
        migrations.AddIndex(
            model_name='postview',
            index=models.Index(fields=['post', '-created_at'], name='posts_postv_post_id_94ab8d_idx'),
        ),
        migrations.AddIndex(
            model_name='postview',
            index=models.Index(fields=['source', '-created_at'], name='posts_postv_source_76d18b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postview',
            unique_together={('user', 'post')},
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', '-created_at'], name='posts_repor_status_648b38_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['reporter', '-created_at'], name='posts_repor_reporte_22005f_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['post', '-created_at'], name='posts_repor_post_id_c6a438_idx'),
        ),
        migrations.AddIndex(
            model_name='save',
            index=models.Index(fields=['user', '-created_at'], name='posts_save_user_id_808924_idx'),
        ),
        migrations.AddIndex(
            model_name='save',
            index=models.Index(fields=['post', '-created_at'], name='posts_save_post_id_cbc54a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='save',
            unique_together={('user', 'post')},
        ),
    ]
