# Generated by Django 5.2.1 on 2025-05-24 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='標題')),
                ('description', models.TextField(verbose_name='描述')),
                ('github_link', models.URLField(blank=True, null=True, verbose_name='GitHub 連結')),
                ('project_link', models.URLField(blank=True, null=True, verbose_name='項目網址')),
                ('youtube_link', models.URLField(blank=True, null=True, verbose_name='YouTube 連結')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '作品集',
                'verbose_name_plural': '作品集',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='portfolio_media/', verbose_name='檔案')),
                ('media_type', models.CharField(choices=[('image', '圖片'), ('video', '影片')], default='image', max_length=10, verbose_name='媒體類型')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='順序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='profiles.portfolio', verbose_name='作品集')),
            ],
            options={
                'verbose_name': '作品集媒體',
                'verbose_name_plural': '作品集媒體',
                'ordering': ['portfolio', 'order'],
            },
        ),
    ]
