# Generated by Django 5.2.1 on 2025-05-24 05:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='評論唯一標識符', primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='評論內容')),
                ('likes_count', models.PositiveIntegerField(default=0, help_text='點讚數量')),
                ('replies_count', models.PositiveIntegerField(default=0, help_text='回覆數量')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否已刪除（軟刪除）')),
                ('is_edited', models.BooleanField(default=False, help_text='是否已編輯')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新時間')),
                ('parent', models.ForeignKey(blank=True, help_text='父評論（用於回覆功能）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comment')),
                ('post', models.ForeignKey(help_text='所屬貼文', on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='posts.post')),
                ('user', models.ForeignKey(help_text='評論作者', on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '評論',
                'verbose_name_plural': '評論',
                'db_table': 'comments_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='點讚時間')),
                ('comment', models.ForeignKey(help_text='被點讚的評論', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='comments.comment')),
                ('user', models.ForeignKey(help_text='點讚用戶', on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '評論點讚',
                'verbose_name_plural': '評論點讚',
                'db_table': 'comments_comment_like',
            },
        ),
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('spam', '垃圾內容'), ('harassment', '騷擾'), ('hate_speech', '仇恨言論'), ('inappropriate', '不當內容'), ('off_topic', '偏離主題'), ('other', '其他')], help_text='舉報原因', max_length=20)),
                ('description', models.TextField(blank=True, help_text='詳細描述')),
                ('status', models.CharField(choices=[('pending', '待處理'), ('reviewed', '已審核'), ('resolved', '已解決'), ('dismissed', '已駁回')], default='pending', help_text='處理狀態', max_length=20)),
                ('reviewer_notes', models.TextField(blank=True, help_text='審核備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='舉報時間')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='審核時間', null=True)),
                ('comment', models.ForeignKey(help_text='被舉報的評論', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='comments.comment')),
                ('reporter', models.ForeignKey(help_text='舉報者', on_delete=django.db.models.deletion.CASCADE, related_name='comment_reports_made', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, help_text='審核者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_reports_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '評論舉報',
                'verbose_name_plural': '評論舉報',
                'db_table': 'comments_comment_report',
            },
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'parent', 'created_at'], name='comments_co_post_id_f27341_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user', '-created_at'], name='comments_co_user_id_4d6386_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', '-created_at'], name='comments_co_post_id_3d4abc_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent', 'created_at'], name='comments_co_parent__10bc81_idx'),
        ),
        migrations.AddIndex(
            model_name='commentlike',
            index=models.Index(fields=['user', '-created_at'], name='comments_co_user_id_8c686d_idx'),
        ),
        migrations.AddIndex(
            model_name='commentlike',
            index=models.Index(fields=['comment', '-created_at'], name='comments_co_comment_f12d1b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together={('user', 'comment')},
        ),
        migrations.AddIndex(
            model_name='commentreport',
            index=models.Index(fields=['status', '-created_at'], name='comments_co_status_9a07bc_idx'),
        ),
        migrations.AddIndex(
            model_name='commentreport',
            index=models.Index(fields=['reporter', '-created_at'], name='comments_co_reporte_347a1c_idx'),
        ),
        migrations.AddIndex(
            model_name='commentreport',
            index=models.Index(fields=['comment', '-created_at'], name='comments_co_comment_fdd426_idx'),
        ),
    ]
