# Generated by Django 5.2.1 on 2025-05-24 06:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='配置鍵', max_length=100, unique=True)),
                ('value', models.JSONField(help_text='配置值')),
                ('config_type', models.CharField(choices=[('general', '一般設置'), ('feature', '功能開關'), ('limit', '限制設置'), ('ui', '界面設置'), ('notification', '通知設置'), ('security', '安全設置')], default='general', help_text='配置類型', max_length=20)),
                ('description', models.TextField(blank=True, help_text='配置描述')),
                ('is_active', models.BooleanField(default=True, help_text='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新時間')),
            ],
            options={
                'verbose_name': '系統配置',
                'verbose_name_plural': '系統配置',
                'db_table': 'core_system_configuration',
                'ordering': ['config_type', 'key'],
            },
        ),
        migrations.CreateModel(
            name='PlatformStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_type', models.CharField(choices=[('daily', '日統計'), ('weekly', '週統計'), ('monthly', '月統計'), ('yearly', '年統計')], help_text='統計類型', max_length=10)),
                ('date', models.DateField(help_text='統計日期')),
                ('total_users', models.PositiveIntegerField(default=0, help_text='總用戶數')),
                ('new_users', models.PositiveIntegerField(default=0, help_text='新增用戶數')),
                ('active_users', models.PositiveIntegerField(default=0, help_text='活躍用戶數')),
                ('total_posts', models.PositiveIntegerField(default=0, help_text='總貼文數')),
                ('new_posts', models.PositiveIntegerField(default=0, help_text='新增貼文數')),
                ('total_comments', models.PositiveIntegerField(default=0, help_text='總評論數')),
                ('new_comments', models.PositiveIntegerField(default=0, help_text='新增評論數')),
                ('total_likes', models.PositiveIntegerField(default=0, help_text='總點讚數')),
                ('total_shares', models.PositiveIntegerField(default=0, help_text='總分享數')),
                ('total_messages', models.PositiveIntegerField(default=0, help_text='總私訊數')),
                ('total_searches', models.PositiveIntegerField(default=0, help_text='總搜尋次數')),
                ('additional_stats', models.JSONField(blank=True, default=dict, help_text='其他統計數據')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='記錄時間')),
            ],
            options={
                'verbose_name': '平台統計',
                'verbose_name_plural': '平台統計',
                'db_table': 'core_platform_statistics',
                'ordering': ['-date', 'stat_type'],
                'indexes': [models.Index(fields=['stat_type', '-date'], name='core_platfo_stat_ty_7f19b7_idx'), models.Index(fields=['-date'], name='core_platfo_date_2e07be_idx')],
                'unique_together': {('stat_type', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ReportedContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('post', '貼文'), ('comment', '評論'), ('user', '用戶'), ('message', '私訊')], help_text='舉報內容類型', max_length=20)),
                ('content_id', models.CharField(help_text='舉報內容ID', max_length=50)),
                ('reason', models.CharField(choices=[('spam', '垃圾訊息'), ('harassment', '騷擾'), ('hate_speech', '仇恨言論'), ('violence', '暴力內容'), ('inappropriate', '不當內容'), ('copyright', '版權侵犯'), ('false_info', '虛假資訊'), ('privacy', '隱私侵犯'), ('other', '其他')], help_text='舉報原因', max_length=20)),
                ('description', models.TextField(blank=True, help_text='詳細描述')),
                ('status', models.CharField(choices=[('pending', '待處理'), ('reviewing', '審核中'), ('resolved', '已解決'), ('dismissed', '已駁回'), ('escalated', '已升級')], default='pending', help_text='處理狀態', max_length=20)),
                ('reviewer_notes', models.TextField(blank=True, help_text='審核備註')),
                ('action_taken', models.CharField(blank=True, help_text='採取的行動', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='舉報時間')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='審核時間', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='解決時間', null=True)),
                ('reporter', models.ForeignKey(help_text='舉報者', on_delete=django.db.models.deletion.CASCADE, related_name='core_reports_made', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, help_text='審核者', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_reports_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '舉報內容',
                'verbose_name_plural': '舉報內容',
                'db_table': 'core_reported_content',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='core_report_status_8ebb20_idx'), models.Index(fields=['content_type', 'content_id'], name='core_report_content_7d4fbe_idx'), models.Index(fields=['reporter'], name='core_report_reporte_916c06_idx'), models.Index(fields=['-created_at'], name='core_report_created_c59c86_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='搜尋記錄唯一標識符', primary_key=True, serialize=False)),
                ('query', models.CharField(help_text='搜尋關鍵字', max_length=200)),
                ('search_type', models.CharField(choices=[('user', '用戶搜尋'), ('post', '貼文搜尋'), ('mixed', '混合搜尋')], help_text='搜尋類型', max_length=10)),
                ('results_count', models.PositiveIntegerField(default=0, help_text='搜尋結果數量')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='搜尋來源IP', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='用戶代理字符串')),
                ('response_time', models.FloatField(blank=True, help_text='搜尋響應時間（毫秒）', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='搜尋時間')),
                ('user', models.ForeignKey(help_text='搜尋用戶', on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '搜尋歷史',
                'verbose_name_plural': '搜尋歷史',
                'db_table': 'core_search_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_search_user_id_5f692d_idx'), models.Index(fields=['query'], name='core_search_query_1574ac_idx'), models.Index(fields=['search_type'], name='core_search_search__4cf250_idx'), models.Index(fields=['-created_at'], name='core_search_created_fa5a64_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('login', '登入'), ('logout', '登出'), ('post_create', '發布貼文'), ('post_like', '點讚貼文'), ('post_comment', '評論貼文'), ('post_share', '分享貼文'), ('post_save', '收藏貼文'), ('user_follow', '關注用戶'), ('user_unfollow', '取消關注'), ('profile_update', '更新個人資料'), ('message_send', '發送訊息'), ('search', '搜尋'), ('page_view', '頁面瀏覽')], help_text='活動類型', max_length=20)),
                ('target_content_type', models.CharField(blank=True, help_text='目標內容類型', max_length=50)),
                ('target_object_id', models.CharField(blank=True, help_text='目標對象ID', max_length=50)),
                ('details', models.JSONField(blank=True, default=dict, help_text='活動詳細數據')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='活動來源IP', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='用戶代理字符串')),
                ('session_key', models.CharField(blank=True, help_text='會話標識', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='活動時間')),
                ('user', models.ForeignKey(help_text='活動用戶', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用戶活動',
                'verbose_name_plural': '用戶活動',
                'db_table': 'core_user_activity',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_user_a_user_id_8175c2_idx'), models.Index(fields=['activity_type'], name='core_user_a_activit_d64453_idx'), models.Index(fields=['-created_at'], name='core_user_a_created_8f4a93_idx'), models.Index(fields=['target_content_type', 'target_object_id'], name='core_user_a_target__ecc270_idx')],
            },
        ),
    ]
