# Generated by Django 4.2.7 on 2025-05-30 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("like", "點讚"),
                            ("comment", "評論"),
                            ("follow", "關注"),
                            ("mention", "提及"),
                            ("message", "私訊"),
                            ("system", "系統通知"),
                            ("post", "貼文相關"),
                            ("achievement", "成就解鎖"),
                        ],
                        help_text="通知類型",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(help_text="通知標題", max_length=200)),
                ("content", models.TextField(help_text="通知內容")),
                (
                    "target_content_type",
                    models.CharField(blank=True, help_text="目標內容類型", max_length=50),
                ),
                (
                    "target_object_id",
                    models.CharField(blank=True, help_text="目標對象ID", max_length=50),
                ),
                (
                    "data",
                    models.JSONField(blank=True, default=dict, help_text="通知附加數據"),
                ),
                ("is_read", models.BooleanField(default=False, help_text="是否已讀")),
                (
                    "read_at",
                    models.DateTimeField(blank=True, help_text="閱讀時間", null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="創建時間"),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="通知接收者",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        help_text="通知發送者",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "通知",
                "verbose_name_plural": "通知",
                "db_table": "core_notification",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "-created_at"],
                        name="core_notifi_recipie_4d7e73_idx",
                    ),
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="core_notifi_recipie_aeffaf_idx",
                    ),
                    models.Index(
                        fields=["notification_type"],
                        name="core_notifi_notific_cbfe88_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="core_notifi_created_f19d5e_idx"
                    ),
                ],
            },
        ),
    ]
